import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../Constants/Colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(10),
    gap: 8,
  },
  backBtn: { padding: 4 },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: moderateScale(10),
    height: moderateScale(40),
    gap: 6,
  },
  searchInput: {
    flex: 1,
    fontSize: moderateScale(14),
    color: colors.textPrimary,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(8),
    gap: 8,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  controlBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(6),
  },
  controlText: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '500',
  },
  resultsCount: {
    marginLeft: 'auto',
    fontSize: moderateScale(12),
    color: colors.textSecondary,
  },
  activeFilters: {
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(8),
    gap: 8,
  },
  activeChip: {
    backgroundColor: '#DBEAFE',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  activeChipText: { fontSize: moderateScale(12), color: colors.primary },
  clearText: {
    fontSize: moderateScale(12),
    color: colors.error,
    fontWeight: '500',
    paddingVertical: 4,
  },
  list: { padding: moderateScale(16), gap: 12 },
  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  cardImage: {
    width: moderateScale(110),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minHeight: moderateScale(100),
  },
  instantBadge: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  instantText: { fontSize: moderateScale(9), color: '#fff', fontWeight: '600' },
  cardInfo: { flex: 1, padding: moderateScale(12) },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 2,
  },
  cardTitle: {
    flex: 1,
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
    marginRight: 8,
  },
  categoryText: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginBottom: 4,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginBottom: 6,
  },
  ratingText: { fontSize: moderateScale(12), color: colors.textSecondary },
  dot: { color: colors.textSecondary },
  distText: { fontSize: moderateScale(12), color: colors.textSecondary },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: moderateScale(15),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  perDay: {
    fontSize: moderateScale(11),
    fontWeight: '400',
    color: colors.textSecondary,
  },
  ownerText: { fontSize: moderateScale(11), color: colors.textSecondary },
  emptyState: { alignItems: 'center', paddingTop: moderateScale(60), gap: 8 },
  emptyTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  emptySubtitle: { fontSize: moderateScale(14), color: colors.textSecondary },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    padding: moderateScale(20),
    paddingBottom: moderateScale(34),
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: moderateScale(16),
  },
  modalTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(16),
  },
  filterLabel: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: { fontSize: moderateScale(13), color: colors.textSecondary },
  filterChipTextActive: { color: '#fff', fontWeight: '600' },
  ratingOptions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: moderateScale(16),
  },
  ratingChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(20),
  },
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#D1D5DB',
    justifyContent: 'center',
    padding: 2,
  },
  toggleActive: { backgroundColor: colors.primary },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  toggleThumbActive: { alignSelf: 'flex-end' },
  applyBtn: {
    backgroundColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingVertical: moderateScale(14),
    alignItems: 'center',
  },
  applyBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  sortOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  sortOptionText: { fontSize: moderateScale(15), color: colors.textPrimary },
  sortOptionActive: { color: colors.primary, fontWeight: '600' },
});
