import { moderateScale } from 'react-native-size-matters';
import { StyleSheet } from 'react-native';
import colors from "../../../Constants/Colors"
export const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: '#fff' },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(12),
      gap: 12,
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    backBtn: { padding: 4 },
    headerTitle: {
      fontSize: moderateScale(18),
      fontWeight: '700',
      color: colors.textPrimary,
    },
    content: { padding: moderateScale(16) },
    trailerSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: moderateScale(10),
      padding: moderateScale(12),
      marginBottom: moderateScale(12),
      backgroundColor: colors.surface,
    },
    trailerSelectorText: {
      flex: 1,
      fontSize: moderateScale(14),
      fontWeight: '600',
      color: colors.textPrimary,
    },
    legend: { flexDirection: 'row', gap: 16, marginBottom: moderateScale(10) },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    legendDot: { width: 12, height: 12, borderRadius: 6 },
    legendText: { fontSize: moderateScale(12), color: colors.textSecondary },
    calendar: {
      borderRadius: moderateScale(14),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: moderateScale(12),
    },
actionsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: moderateScale(20),
    },
    blockBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: colors.error,
      borderRadius: moderateScale(10),
      paddingVertical: moderateScale(11),
    },
    blockBtnText: {
      color: colors.error,
      fontSize: moderateScale(14),
      fontWeight: '600',
    },
    clearBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: moderateScale(10),
      paddingVertical: moderateScale(11),
    },
    clearBtnText: { color: colors.textSecondary, fontSize: moderateScale(14) },
    sectionTitle: {
      fontSize: moderateScale(16),
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: moderateScale(10),
    },
    rulesCard: {
      backgroundColor: colors.surface,
      borderRadius: moderateScale(14),
      padding: moderateScale(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: moderateScale(12),
    },
    ruleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: moderateScale(10),
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
      ruleLabel: { fontSize: moderateScale(14), color: colors.textPrimary },
    ruleCounter: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    ruleValue: {
      fontSize: moderateScale(18),
      fontWeight: '700',
      color: colors.textPrimary,
      minWidth: moderateScale(24),
      textAlign: 'center',
    },
    recurringCard: {
      backgroundColor: colors.surface,
      borderRadius: moderateScale(14),
      padding: moderateScale(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: moderateScale(20),
    },
    recurringRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    recurringTitle: {
      fontSize: moderateScale(14),
      fontWeight: '700',
      color: colors.textPrimary,
    },
    recurringSubtitle: {
      fontSize: moderateScale(12),
      color: colors.textSecondary,
      marginTop: 2,
    },
    recurringNote: {
      fontSize: moderateScale(12),
      color: colors.textSecondary,
      marginTop: 10,
      lineHeight: 18,
    },
    saveBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      borderRadius: moderateScale(12),
      paddingVertical: moderateScale(14),
    },
  saveBtnText: {
      color: '#fff',
      fontSize: moderateScale(15),
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: '#fff',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: moderateScale(16),
      paddingBottom: moderateScale(30),
    },
    modalHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: '#D1D5DB',
      alignSelf: 'center',
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: moderateScale(17),
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: 4,
    },
    modalSubtitle: {
      fontSize: moderateScale(13),
      color: colors.textSecondary,
      marginBottom: 12,
    },
    dateDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      marginBottom: 12,
    },
    dateBox: { alignItems: 'center' },
    dateBoxLabel: {
      fontSize: moderateScale(11),
      color: colors.textSecondary,
      fontWeight: '600',
    },
       dateBoxValue: {
      fontSize: moderateScale(14),
      fontWeight: '700',
      color: colors.textPrimary,
      marginTop: 4,
    },
    applyBtn: {
      backgroundColor: '#E53935',
      borderRadius: moderateScale(12),
      paddingVertical: moderateScale(13),
      alignItems: 'center',
      marginTop: 12,
    },
    applyBtnText: {
      color: '#fff',
      fontSize: moderateScale(15),
      fontWeight: '700',
    },
    cancelLink: { alignItems: 'center', paddingVertical: moderateScale(10) },
    cancelLinkText: {
      fontSize: moderateScale(14),
      color: colors.textSecondary,
    },
    trailerOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: moderateScale(14),
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    trailerOptionText: {
      fontSize: moderateScale(15),
      color: colors.textPrimary,
    },





})