import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    flex: 1,
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
  },
  statChip: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: moderateScale(10),
    borderRadius: moderateScale(10),
    borderWidth: 1.5,
  },
  statNum: { fontSize: moderateScale(20), fontWeight: '800' },
  statLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: colors.border,
    marginHorizontal: moderateScale(16),
  },
  tab: {
    flex: 1,
    paddingVertical: moderateScale(10),
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: 'transparent',
  },
  tabActive: { borderBottomColor: colors.primary },
  tabText: {
    fontSize: moderateScale(14),
    color: colors.textSecondary,
    fontWeight: '500',
  },
  tabTextActive: { color: colors.primary, fontWeight: '700' },
  list: { padding: moderateScale(16), gap: 12 },
  card: {
    backgroundColor: '#fff',
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  cardTop: { padding: moderateScale(14), gap: 10 },
  renterRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatar: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: moderateScale(16),
    fontWeight: '700',
  },
  renterInfo: { flex: 1 },
  renterNameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  renterName: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 2,
  },
  metaText: { fontSize: moderateScale(12), color: colors.textSecondary },
  statusBadge: { borderRadius: 4, paddingHorizontal: 7, paddingVertical: 3 },
  statusText: { fontSize: moderateScale(10), fontWeight: '700' },
  trailerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.surface,
    borderRadius: moderateScale(8),
    padding: moderateScale(8),
  },
  trailerThumb: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailerName: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  trailerType: { fontSize: moderateScale(11), color: colors.textSecondary },
  detailsGrid: { gap: 5 },
  detailItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailText: { fontSize: moderateScale(12), color: colors.textSecondary },
  returnBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF9C3',
    borderRadius: 8,
    padding: 8,
  },
  returnBannerText: {
    flex: 1,
    fontSize: moderateScale(12),
    color: '#92400E',
    fontWeight: '500',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    padding: moderateScale(12),
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  returnBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#F0FDF4',
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(9),
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  returnBtnText: {
    color: colors.success,
    fontSize: moderateScale(13),
    fontWeight: '700',
  },
  msgBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(9),
  },
  msgBtnText: {
    color: colors.primary,
    fontSize: moderateScale(13),
    fontWeight: '600',
  },
  emptyState: { alignItems: 'center', paddingTop: moderateScale(60), gap: 8 },
  emptyTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: colors.textSecondary,
  },
});
