import { StyleSheet } from 'react-native';

import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  content: { padding: moderateScale(16) },
  overallCard: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    marginBottom: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  overallLeft: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: moderateScale(16),
    borderRightWidth: 1,
    borderColor: colors.border,
    marginRight: moderateScale(16),
  },
  overallRating: {
    fontSize: moderateScale(48),
    fontWeight: '900',
    color: colors.textPrimary,
    lineHeight: moderateScale(52),
  },
  overallCount: { fontSize: moderateScale(12), color: colors.textSecondary },
  overallRight: { flex: 1, justifyContent: 'center', gap: 4 },
  breakdownRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  breakdownStar: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    width: moderateScale(10),
  },
  breakdownBar: {
    flex: 1,
    height: 6,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    overflow: 'hidden',
  },
  breakdownFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: 3,
  },
  breakdownCount: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    width: moderateScale(20),
    textAlign: 'right',
  },
  trustCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#F0FDF4',
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    marginBottom: moderateScale(20),
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  trustInfo: { flex: 1 },
  trustTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.success,
  },
  trustSubtitle: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
    lineHeight: 18,
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(12),
  },
  reviewCard: {
    backgroundColor: '#fff',
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 10,
  },
  reviewAvatar: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewAvatarText: {
    color: '#fff',
    fontSize: moderateScale(16),
    fontWeight: '700',
  },
  reviewMeta: { flex: 1 },
  reviewRenterName: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  reviewRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
  },
  reviewDate: { fontSize: moderateScale(11), color: colors.textSecondary },
  reviewTrailer: {
    fontSize: moderateScale(12),
    color: colors.primary,
    fontWeight: '500',
    marginTop: 2,
  },
  reviewText: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: 8,
  },
  helpfulRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  helpfulText: { fontSize: moderateScale(11), color: colors.textSecondary },
});
