import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from "../../../Constants/Colors"
const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(12), gap: 12, borderBottomWidth: 1, borderColor: colors.border },
  backBtn: { padding: 4 },
  headerTitle: { flex: 1, fontSize: moderateScale(18), fontWeight: '700', color: colors.textPrimary },
  refText: { fontSize: moderateScale(11), color: colors.textSecondary },
  expiryBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FEF9C3', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(10) },
  expiryText: { flex: 1, fontSize: moderateScale(13), color: '#92400E', fontWeight: '500' },
  content: { padding: moderateScale(16), gap: 12 },
  card: { backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), borderWidth: 1, borderColor: colors.border },
  cardTitle: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary, marginBottom: moderateScale(12) },
  renterRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 },
  avatar: { width: moderateScale(48), height: moderateScale(48), borderRadius: moderateScale(24), backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontSize: moderateScale(18), fontWeight: '700' },
  renterInfo: { flex: 1 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  renterName: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary },
  verifiedChip: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#F0FDF4', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, borderWidth: 1, borderColor: '#BBF7D0' },
  verifiedText: { fontSize: moderateScale(10), color: colors.success, fontWeight: '600' },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  metaText: { fontSize: moderateScale(12), color: colors.textSecondary },
  dot: { color: colors.textSecondary },
  noteBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#fff', borderRadius: 8, padding: 10, borderWidth: 1, borderColor: colors.border },
  noteText: { flex: 1, fontSize: moderateScale(13), color: colors.textSecondary, fontStyle: 'italic' },
  trailerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  trailerThumb: { width: moderateScale(52), height: moderateScale(52), borderRadius: moderateScale(10), alignItems: 'center', justifyContent: 'center' },
  trailerName: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary },
  trailerType: { fontSize: moderateScale(12), color: colors.textSecondary, marginTop: 2 },
  datesRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', marginBottom: 10 },
  dateItem: { alignItems: 'center' },
  dateLabel: { fontSize: moderateScale(11), color: colors.textSecondary, fontWeight: '600', textTransform: 'uppercase' },
  dateValue: { fontSize: moderateScale(14), fontWeight: '700', color: colors.textPrimary, marginTop: 4 },
  durationBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fff', borderRadius: 20, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 10, paddingVertical: 5, alignSelf: 'center' },
  durationText: { fontSize: moderateScale(12), color: colors.textSecondary },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderColor: colors.border },
  priceLabel: { fontSize: moderateScale(13), color: colors.textSecondary },
  priceValue: { fontSize: moderateScale(13), color: colors.textPrimary, fontWeight: '600' },
  totalRow: { borderBottomWidth: 0, paddingTop: 10 },
  totalLabel: { fontSize: moderateScale(15), fontWeight: '800', color: colors.textPrimary },
  totalValue: { fontSize: moderateScale(18), fontWeight: '800', color: colors.success },
  actionBar: { flexDirection: 'row', gap: 10, padding: moderateScale(16), borderTopWidth: 1, borderColor: colors.border, backgroundColor: '#fff' },
  rejectBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1.5, borderColor: colors.error, borderRadius: moderateScale(12), paddingVertical: moderateScale(13) },
  rejectBtnText: { color: colors.error, fontSize: moderateScale(14), fontWeight: '700' },
  approveBtn: { flex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: colors.success, borderRadius: moderateScale(12), paddingVertical: moderateScale(13) },
  approveBtnText: { color: '#fff', fontSize: moderateScale(14), fontWeight: '700' },
  btnDisabled: { opacity: 0.6 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: moderateScale(20), paddingBottom: moderateScale(34) },
  modalHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#D1D5DB', alignSelf: 'center', marginBottom: 16 },
  modalTitle: { fontSize: moderateScale(17), fontWeight: '700', color: colors.textPrimary, marginBottom: moderateScale(14) },
  reasonOption: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: moderateScale(12), borderBottomWidth: 1, borderColor: colors.border },
  radioBtn: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  radioBtnActive: { borderColor: colors.primary },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.primary },
  reasonText: { flex: 1, fontSize: moderateScale(14), color: colors.textPrimary },
  confirmRejectBtn: { backgroundColor: colors.error, borderRadius: moderateScale(12), paddingVertical: moderateScale(14), alignItems: 'center', marginTop: moderateScale(16) },
  confirmRejectBtnText: { color: '#fff', fontSize: moderateScale(15), fontWeight: '700' },
  cancelBtn: { alignItems: 'center', paddingVertical: moderateScale(12) },
  cancelBtnText: { fontSize: moderateScale(14), color: colors.textSecondary },
});