import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
import Fonts from '../../../Theme/Fonts';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  photoCarousel: { height: moderateScale(320), position: 'relative' },
  photoSlide: {
    width: moderateScale(375),
    height: moderateScale(320),
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayControls: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(8),
  },
  overlayBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(8),
    gap: moderateScale(10),
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  overlaySearch: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textPrimary,
    paddingVertical: 0,
  },
  photoCountPill: {
    position: 'absolute',
    bottom: moderateScale(14),
    right: moderateScale(16),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(5),
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: moderateScale(18),
    paddingVertical: moderateScale(8),
  },
  photoCountText: {
    color: colors.primary,
    fontSize: moderateScale(13),
    fontWeight: '600',
  },
  photoModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  photoModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  photoModalTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  photoModalClose: {
    padding: 4,
  },
  photoModalList: {
    padding: moderateScale(16),
    gap: moderateScale(12),
  },
  photoModalItem: {
    height: moderateScale(180),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    gap: moderateScale(8),
  },
  photoModalIndex: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    fontWeight: '500',
  },
  content: { flex: 1 },
  titleBlock: {
    padding: moderateScale(16),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  titleMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: moderateScale(16),
  },
  titleLeft: {
    flex: 1,
    marginRight: moderateScale(12),
    gap: moderateScale(4),
  },
  titleRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(3),
  },
  trailerTitle: {
    fontSize: moderateScale(22),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  trailerAddress: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  trailerCapacity: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  ratingText: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: '#F59E0B',
  },
  reviewCount: { fontSize: moderateScale(13), color: colors.textSecondary },
  pricingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: moderateScale(10),
  },
  pricingAmount: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.primaryDark,
  },
  pricingUnit: {
    fontSize: moderateScale(15),
    color: colors.textSecondary,
    fontWeight: '400',
  },
  pricingDivider: {
    width: 1,
    height: moderateScale(32),
    backgroundColor: colors.border,
  },
  card: {
    // margin: moderateScale(4),
    marginBottom: 0,
    padding: moderateScale(16),
    // backgroundColor: colors.surface,
    // borderRadius: moderateScale(14),
    // borderWidth: 1,
    // borderColor: colors.border,
  },
  cardTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(12),
  },
  ownerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: moderateScale(18), fontWeight: '700' },
  ownerInfo: { flex: 1 },
  ownerName: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  ownerRating: { fontSize: moderateScale(12), color: colors.textSecondary },
  responseTime: {
    fontSize: moderateScale(12),
    color: colors.success,
    marginTop: 2,
  },
  msgBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  msgText: {
    fontSize: moderateScale(12),
    color: colors.primary,
    fontWeight: '600',
  },
  priceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: moderateScale(10),
  },
  priceItem: { alignItems: 'center' },
  priceBig: {
    fontSize: moderateScale(20),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  priceLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  priceDivider: { width: 1, backgroundColor: colors.border },
  feeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
    padding: 8,
  },
  feeText: {
    flex: 1,
    fontSize: moderateScale(12),
    color: colors.textSecondary,
  },
  specsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  specItem: {
    width: '44%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  specValue: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 4,
  },
  specLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  description: {
    fontSize: moderateScale(14),
    color: colors.textSecondary,
    lineHeight: 20,
  },
  expandText: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '600',
    marginTop: 6,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  ruleText: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  towingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: moderateScale(16),
    marginBottom: 0,
    padding: moderateScale(16),
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  towingLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  towingTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.primary,
  },
  towingSubtitle: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  bookBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: moderateScale(16),
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  bookPrice: {
    fontSize: moderateScale(20),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  bookPerDay: {
    fontSize: moderateScale(14),
    fontWeight: '400',
    color: colors.textSecondary,
  },
  bookNote: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  bookBtn: {
    // flexDirection: 'row',
    // alignItems: 'center',
    // gap: 2,
    // backgroundColor: colors.primary,
    // borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(20),
    paddingVertical: moderateScale(3),
 
  },
  bookBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  categoryText: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    fontWeight: '400',
  },
  DescratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Rentercard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: moderateScale(14),
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(12),
    marginBottom: moderateScale(0),
    width: '100%',
  },
  RentercardRow: { gap: moderateScale(12) },
  RentercardTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  RentercardSub: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: moderateScale(3),
  },
  locationCard: {
    marginTop: moderateScale(0),
    marginLeft: moderateScale(16),
    marginRight: moderateScale(16),
    marginBottom: 0,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(14),
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  locationCardTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    paddingHorizontal: moderateScale(14),
    paddingTop: moderateScale(14),
    paddingBottom: moderateScale(6),
  },
  locationAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(14),
    paddingBottom: moderateScale(12),
    gap: moderateScale(8),
  },
  locationAddress: {
    flex: 1,
    fontSize: moderateScale(14),
    color: colors.textSecondary,
  },
  mapPlaceholder: {
    height: moderateScale(160),
    backgroundColor: '#e8e0d0',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: moderateScale(2),
    marginRight: moderateScale(12),
    marginLeft: moderateScale(12),
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(10),
  },
  mapStreetH1: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '38%',
    height: moderateScale(8),
    backgroundColor: '#fff',
    opacity: 0.8,
  },
  mapStreetH2: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '65%',
    height: moderateScale(5),
    backgroundColor: '#fff',
    opacity: 0.6,
  },
  mapStreetV1: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '30%',
    width: moderateScale(8),
    backgroundColor: '#fff',
    opacity: 0.8,
  },
  mapStreetV2: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '65%',
    width: moderateScale(5),
    backgroundColor: '#fff',
    opacity: 0.6,
  },
  mapPinWrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  // section
  section: {
    marginTop: moderateScale(30),
    marginLeft: moderateScale(12),
    marginRight: moderateScale(12),
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: moderateScale(10),
  },
  sectionTitle: {
    fontSize: Fonts.size.xl,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  seeAll: {
    fontSize: Fonts.size.sm,
    fontWeight: '600',
    color: colors.primary,
  },

  // view all specs
  viewAllBtn: {
    marginTop: moderateScale(12),
    // marginLeft: moderateScale(12),
    marginRight: moderateScale(12),
    paddingVertical: moderateScale(10),
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  viewAllText: {
    fontSize: Fonts.size.sm,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  Ratingcard: {
    marginBottom: 0,
    padding: moderateScale(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  RatingcardTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(12),
  },
  RatingReviewsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingBreakdownCard: {
    paddingHorizontal: moderateScale(16),
    paddingBottom: moderateScale(16),
    gap: moderateScale(10),
  },
  ratingBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(10),
  },
  ratingBreakdownLabel: {
    width: moderateScale(100),
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  ratingBarTrack: {
    flex: 1,
    height: moderateScale(8),
    backgroundColor: '#E5E7EB',
    borderRadius: moderateScale(4),
    overflow: 'hidden',
  },
  ratingBarFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: moderateScale(4),
  },
  ratingBreakdownValue: {
    width: moderateScale(28),
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'right',
  },

  // Reviews
  reviewsSection: {
    paddingHorizontal: moderateScale(16),
    paddingBottom: moderateScale(8),
  },
  reviewItem: {
    paddingVertical: moderateScale(14),
    gap: moderateScale(8),
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(10),
  },
  reviewAvatar: {
    width: moderateScale(46),
    height: moderateScale(46),
    borderRadius: moderateScale(23),
    backgroundColor: '#E5E7EB',
  },
  reviewAuthorInfo: {
    flex: 1,
  },
  reviewAuthorName: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  reviewDate: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: moderateScale(1),
  },
  reviewStarsRow: {
    flexDirection: 'row',
    gap: moderateScale(2),
  },
  reviewText: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    lineHeight: moderateScale(19),
  },
  reviewDivider: {
    marginHorizontal: 0,
  },
  showAllReviewsBtn: {
    marginTop: moderateScale(12),
    marginBottom: moderateScale(4),
    paddingVertical: moderateScale(12),
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  showAllReviewsText: {
    fontSize: Fonts.size.sm,
    fontWeight: '600',
    color: colors.textPrimary,
  },

  // Info Tabs
  infoTabsWrapper: {
    marginTop: moderateScale(8),
  },
  infoTabBar: {
    flexDirection: 'row',
    paddingHorizontal: moderateScale(16),
    gap: moderateScale(24),
    paddingBottom: moderateScale(2),
  },
  infoTabItem: {
    alignItems: 'center',
    paddingVertical: moderateScale(10),
  },
  infoTabLabel: {
    fontSize: moderateScale(13),
    fontWeight: '500',
    color: colors.textSecondary,
  },
  infoTabLabelActive: {
    fontWeight: '700',
    color: colors.textPrimary,
  },
  infoTabUnderline: {
    marginTop: moderateScale(4),
    height: moderateScale(2),
    width: '100%',
    backgroundColor: colors.textPrimary,
    borderRadius: moderateScale(2),
  },
  infoTabContent: {
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(14),
    paddingBottom: moderateScale(8),
    gap: moderateScale(14),
  },
  infoTabDivider: {
    marginTop: moderateScale(8),
  },
  // Cancellation rules
  infoRuleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: moderateScale(10),
  },
  infoRuleText: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    lineHeight: moderateScale(19),
  },
  // Payment options
  infoPaymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(12),
    paddingVertical: moderateScale(4),
  },
  infoPaymentIcon: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(10),
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoPaymentLabel: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  infoPaymentSub: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: moderateScale(2),
  },
  // Report listing
  infoReportHeading: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: moderateScale(4),
  },
  infoReportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(10),
    paddingVertical: moderateScale(6),
  },
  infoReportRadio: {
    width: moderateScale(18),
    height: moderateScale(18),
    borderRadius: moderateScale(9),
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoReportRadioFill: {
    width: moderateScale(9),
    height: moderateScale(9),
    borderRadius: moderateScale(5),
    backgroundColor: colors.primary,
  },
  infoReportText: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },

  // Similar Trailers
  similarSection: {
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(20),
  },
  similarTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(14),
  },
  similarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: moderateScale(12),
  },
  similarCard: {
    width: '47%',
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  similarImageBox: {
    height: moderateScale(100),
    alignItems: 'center',
    justifyContent: 'center',
  },
  similarName: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: moderateScale(8),
    paddingHorizontal: moderateScale(8),
  },
  similarDistance: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: moderateScale(2),
    paddingHorizontal: moderateScale(8),
  },
  similarSpecs: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    paddingHorizontal: moderateScale(8),
  },
  similarPrice: {
    paddingHorizontal: moderateScale(8),
    paddingBottom: moderateScale(10),
    marginTop: moderateScale(4),
  },
  similarPriceAmount: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  similarPriceUnit: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    fontWeight: '400',
  },
  similarPriceWeekAmount: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.primaryDark,
  },
});
