import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  photoCarousel: { height: moderateScale(320), position: 'relative' },
  photoSlide: {
    width: moderateScale(375),
    height: moderateScale(320),
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayControls: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(8),
  },
  overlayBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(8),
    gap: moderateScale(10),
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  overlaySearch: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textPrimary,
    paddingVertical: 0,
  },
  photoCountPill: {
    position: 'absolute',
    bottom: moderateScale(14),
    right: moderateScale(16),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(5),
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: moderateScale(18),
    paddingVertical: moderateScale(8),
  },
  photoCountText: {
    color: colors.primary,
    fontSize: moderateScale(13),
    fontWeight: '600',
  },
  photoModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  photoModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  photoModalTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  photoModalClose: {
    padding: 4,
  },
  photoModalList: {
    padding: moderateScale(16),
    gap: moderateScale(12),
  },
  photoModalItem: {
    height: moderateScale(180),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    gap: moderateScale(8),
  },
  photoModalIndex: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    fontWeight: '500',
  },
  content: { flex: 1 },
  titleBlock: {
    padding: moderateScale(16),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  titleMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: moderateScale(16),
  },
  titleLeft: {
    flex: 1,
    marginRight: moderateScale(12),
    gap: moderateScale(4),
  },
  titleRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(3),
  },
  trailerTitle: {
    fontSize: moderateScale(22),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  trailerAddress: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  trailerCapacity: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  ratingText: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: '#F59E0B',
  },
  reviewCount: { fontSize: moderateScale(13), color: colors.textSecondary },
  pricingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: moderateScale(10),
  },
  pricingAmount: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.primaryDark,
  },
  pricingUnit: {
    fontSize: moderateScale(15),
    color: colors.textSecondary,
    fontWeight: '400',
  },
  pricingDivider: {
    width: 1,
    height: moderateScale(32),
    backgroundColor: colors.border,
  },
  card: {
    margin: moderateScale(16),
    marginBottom: 0,
    padding: moderateScale(16),
    backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(12),
  },
  ownerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: moderateScale(18), fontWeight: '700' },
  ownerInfo: { flex: 1 },
  ownerName: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  ownerRating: { fontSize: moderateScale(12), color: colors.textSecondary },
  responseTime: {
    fontSize: moderateScale(12),
    color: colors.success,
    marginTop: 2,
  },
  msgBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  msgText: {
    fontSize: moderateScale(12),
    color: colors.primary,
    fontWeight: '600',
  },
  priceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: moderateScale(10),
  },
  priceItem: { alignItems: 'center' },
  priceBig: {
    fontSize: moderateScale(20),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  priceLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  priceDivider: { width: 1, backgroundColor: colors.border },
  feeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
    padding: 8,
  },
  feeText: {
    flex: 1,
    fontSize: moderateScale(12),
    color: colors.textSecondary,
  },
  specsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  specItem: {
    width: '44%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  specValue: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 4,
  },
  specLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  description: {
    fontSize: moderateScale(14),
    color: colors.textSecondary,
    lineHeight: 20,
  },
  expandText: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '600',
    marginTop: 6,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  ruleText: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  towingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: moderateScale(16),
    marginBottom: 0,
    padding: moderateScale(16),
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  towingLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  towingTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.primary,
  },
  towingSubtitle: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  bookBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: moderateScale(16),
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  bookPrice: {
    fontSize: moderateScale(20),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  bookPerDay: {
    fontSize: moderateScale(14),
    fontWeight: '400',
    color: colors.textSecondary,
  },
  bookNote: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  bookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(20),
    paddingVertical: moderateScale(13),
  },
  bookBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  categoryText: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    fontWeight: '400',
  },
  DescratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
});
