import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  scrollContent: { padding: moderateScale(16) },
  trailerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(12),
    padding: moderateScale(14),
    marginBottom: moderateScale(20),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  trailerCardInfo: { flex: 1 },
  trailerCardTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  trailerCardSub: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(14),
  },
  fieldLabel: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  pickerBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(10),
    paddingHorizontal: moderateScale(14),
    height: moderateScale(48),
    marginBottom: moderateScale(14),
    backgroundColor: colors.surface,
  },
  pickerBtnDisabled: { opacity: 0.5 },
  pickerBtnText: { fontSize: moderateScale(14), color: colors.textPrimary },
  placeholder: { color: '#9CA3AF' },
  inputRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(10),
    paddingHorizontal: moderateScale(14),
    height: moderateScale(48),
    marginBottom: moderateScale(14),
    backgroundColor: colors.surface,
    justifyContent: 'center',
  },
  textInput: { fontSize: moderateScale(14), color: colors.textPrimary },
  checkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingVertical: moderateScale(14),
    marginTop: moderateScale(4),
    marginBottom: moderateScale(20),
  },
  checkBtnDisabled: { backgroundColor: '#93C5FD' },
  checkBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  resultCard: {
    borderWidth: 2,
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    gap: 12,
  },
  resultHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  resultHeaderInfo: { flex: 1 },
  resultLabel: { fontSize: moderateScale(18), fontWeight: '800' },
  confidenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  confidenceBar: { height: 4, borderRadius: 2 },
  confidenceText: { fontSize: moderateScale(12), color: colors.textSecondary },
  resultMessage: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    lineHeight: 20,
  },
  ackRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  checkboxActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  ackText: {
    flex: 1,
    fontSize: moderateScale(13),
    color: colors.textSecondary,
  },
  proceedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: moderateScale(10),
    paddingVertical: moderateScale(12),
  },
  proceedBtnText: {
    color: '#fff',
    fontSize: moderateScale(14),
    fontWeight: '700',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: moderateScale(20),
    maxHeight: '60%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  pickerOption: {
    paddingVertical: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  pickerOptionText: { fontSize: moderateScale(15), color: colors.textPrimary },
});
