import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(10),
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: colors.border,
    height: moderateScale(44),
    paddingHorizontal: moderateScale(8),
  },
  searchBarArrow: {
    padding: moderateScale(4),
  },
  searchBarLocation: {
    flex: 1,
    textAlign: 'center',
    fontSize: moderateScale(14),
    color: colors.textPrimary,
    fontWeight: '500',
  },
  searchBarFilter: {
    padding: moderateScale(4),
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(8),
    gap: 8,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  controlBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(6),
  },
  controlText: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '500',
  },
  activeFilters: {
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(8),
    gap: 8,
  },
  activeChip: {
    backgroundColor: '#DBEAFE',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  activeChipText: { fontSize: moderateScale(12), color: colors.primary },
  clearText: {
    fontSize: moderateScale(12),
    color: colors.error,
    fontWeight: '500',
    paddingVertical: 4,
  },
  list: { padding: moderateScale(16), gap: 12 },
  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  cardImage: {
    width: moderateScale(100),
    minHeight: moderateScale(100),
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardInfo: { flex: 1, padding: moderateScale(12), justifyContent: 'center' },
  cardTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 3,
  },
  cardSubtitle: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginBottom: 2,
  },
  cardSpecs: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginBottom: 8,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  perDay: {
    fontSize: moderateScale(11),
    fontWeight: '400',
    color: colors.textSecondary,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  ratingText: { fontSize: moderateScale(12), color: colors.textSecondary },
  resultsTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(8),
    paddingBottom: moderateScale(4),
  },
  emptyState: { alignItems: 'center', paddingTop: moderateScale(60), gap: 8 },
  emptyTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  emptySubtitle: { fontSize: moderateScale(14), color: colors.textSecondary },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    padding: moderateScale(20),
    paddingBottom: moderateScale(34),
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: moderateScale(16),
  },
  modalTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(16),
  },
  filterLabel: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  filterModalSafe: { flex: 1, backgroundColor: '#fff' },
  filterModalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
  },
  filterModalSheet: {
    height: '50%',
    backgroundColor: '#fff',
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    overflow: 'hidden',
  },
  filterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(14),
  },
  filterModalTitle: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  filterModalClose: {
    position: 'absolute',
    right: moderateScale(16),
    padding: 4,
  },
  filterDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  filterModalBody: { flex: 1 },
  accordionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(16),
  },
  accordionTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  accordionContent: {
    paddingHorizontal: moderateScale(16),
    paddingBottom: moderateScale(16),
  },
  categoryChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(20),
    paddingVertical: moderateScale(16),
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
  },
  clearAllText: {
    fontSize: moderateScale(15),
    color: colors.textPrimary,
    fontWeight: '500',
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: { fontSize: moderateScale(13), color: colors.textSecondary },
  filterChipTextActive: { color: '#fff', fontWeight: '600' },
  ratingOptions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: moderateScale(16),
  },
  ratingChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(20),
  },
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#D1D5DB',
    justifyContent: 'center',
    padding: 2,
  },
  toggleActive: { backgroundColor: colors.primary },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  toggleThumbActive: { alignSelf: 'flex-end' },
  applyBtn: {
    backgroundColor: '#111827',
    borderRadius: moderateScale(24),
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(32),
    alignItems: 'center',
  },
  applyBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  sortOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  sortOptionText: { fontSize: moderateScale(15), color: colors.textPrimary },
  sortOptionActive: { color: colors.primary, fontWeight: '600' },
});
