import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from "../../../Constants/Colors"
export const styles =  StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(12), gap: 12, borderBottomWidth: 1, borderColor: colors.border },
  backBtn: { padding: 4 },
  headerTitle: { flex: 1, fontSize: moderateScale(18), fontWeight: '700', color: colors.textPrimary },
  content: { padding: moderateScale(16) },
  summaryRow: { flexDirection: 'row', gap: 8, marginBottom: moderateScale(12) },
  summaryCard: { flex: 1, borderRadius: moderateScale(12), padding: moderateScale(12) },
  summaryLabel: { fontSize: moderateScale(10), color: colors.textSecondary, fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  summaryValue: { fontSize: moderateScale(18), fontWeight: '800' },
  nextPayoutCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#EFF6FF', borderRadius: moderateScale(14), padding: moderateScale(16), marginBottom: moderateScale(20), borderWidth: 1, borderColor: '#BFDBFE' },
  nextPayoutLabel: { fontSize: moderateScale(12), color: colors.textSecondary, fontWeight: '600', marginBottom: 4 },
  nextPayoutAmount: { fontSize: moderateScale(28), fontWeight: '900', color: colors.primary },
  nextPayoutDate: { fontSize: moderateScale(12), color: colors.textSecondary, marginTop: 2 },
  payoutSettingsBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fff', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: '#BFDBFE' },
  payoutSettingsText: { fontSize: moderateScale(12), color: colors.primary, fontWeight: '600' },
  sectionTitle: { fontSize: moderateScale(16), fontWeight: '700', color: colors.textPrimary, marginBottom: moderateScale(10) },
  chartCard: { backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), marginBottom: moderateScale(20), borderWidth: 1, borderColor: colors.border },
  barChart: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', height: moderateScale(110) },
  barItem: { alignItems: 'center', gap: 4 },
  barAmount: { fontSize: moderateScale(10), color: colors.textSecondary },
  barTrack: { height: moderateScale(80), justifyContent: 'flex-end' },
  bar: { width: moderateScale(32), borderRadius: 4 },
  barLabel: { fontSize: moderateScale(11), color: colors.textSecondary },
  periodTabs: { flexDirection: 'row', gap: 8, marginBottom: moderateScale(16) },
  periodTab: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, borderWidth: 1, borderColor: colors.border },
  periodTabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  periodTabText: { fontSize: moderateScale(13), color: colors.textSecondary },
  periodTabTextActive: { color: '#fff', fontWeight: '600' },
  earningRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingVertical: moderateScale(12), borderBottomWidth: 1, borderColor: colors.border },
  earningLeft: { flex: 1 },
  earningRenter: { fontSize: moderateScale(14), fontWeight: '700', color: colors.textPrimary },
  earningTrailer: { fontSize: moderateScale(12), color: colors.textSecondary, marginTop: 2 },
  earningDates: { fontSize: moderateScale(11), color: colors.textSecondary, marginTop: 2 },
  earningRight: { alignItems: 'flex-end', gap: 4 },
  earningNet: { fontSize: moderateScale(16), fontWeight: '800', color: colors.success },
  payoutBadge: { borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2 },
  payoutBadgeText: { fontSize: moderateScale(11), fontWeight: '700' },
  depositTag: { fontSize: moderateScale(10), color: colors.textSecondary },
  downloadBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1.5, borderColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(13), marginTop: moderateScale(20) },
  downloadBtnText: { color: colors.primary, fontSize: moderateScale(14), fontWeight: '600' },
});