import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  content: { padding: moderateScale(16), gap: 12 },
  summaryCard: {
    backgroundColor: '#F0FDF4',
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  summaryInfo: { flex: 1 },
  summaryLabel: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    fontWeight: '600',
  },
  summaryAmount: {
    fontSize: moderateScale(28),
    fontWeight: '900',
    color: colors.success,
  },
  summaryDate: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(12),
  },
  cardTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  editLink: {
    fontSize: moderateScale(14),
    color: colors.primary,
    fontWeight: '600',
  },
  bankDisplay: { gap: 10 },
  bankIconRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  bankName: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  bankAccount: {
    fontSize: moderateScale(13),
    color: colors.textSecondary,
    marginTop: 2,
  },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  verifiedText: {
    fontSize: moderateScale(12),
    color: colors.success,
    fontWeight: '600',
  },
  bankForm: { gap: 4 },
  fieldLabel: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: 8,
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    height: moderateScale(46),
    fontSize: moderateScale(14),
    color: colors.textPrimary,
    backgroundColor: '#fff',
  },
  encryptionNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
  },
  encryptionText: {
    flex: 1,
    fontSize: moderateScale(12),
    color: colors.textSecondary,
  },
  saveAccountBtn: {
    backgroundColor: colors.primary,
    borderRadius: moderateScale(10),
    paddingVertical: moderateScale(12),
    alignItems: 'center',
    marginTop: 12,
  },
  saveAccountBtnText: {
    color: '#fff',
    fontSize: moderateScale(14),
    fontWeight: '700',
  },
  scheduleOption: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: moderateScale(12),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  radioActive: { borderColor: colors.primary },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  scheduleInfo: { flex: 1 },
  scheduleLabel: { fontSize: moderateScale(14), color: colors.textPrimary },
  scheduleDesc: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(12),
    padding: moderateScale(14),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  infoText: { flex: 1 },
  infoTitle: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 4,
  },
  infoDesc: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    lineHeight: 18,
  },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingVertical: moderateScale(14),
    alignItems: 'center',
  },
  saveBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
});
