import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  content: { padding: moderateScale(20) },
  successSection: { alignItems: 'center', paddingVertical: moderateScale(24) },
  successCircle: { marginBottom: moderateScale(16) },
  successTitle: { fontSize: moderateScale(26), fontWeight: '800', color: colors.textPrimary, marginBottom: 8 },
  successSubtitle: { fontSize: moderateScale(14), color: colors.textSecondary, textAlign: 'center', lineHeight: 20 },
  refCard: { backgroundColor: '#EFF6FF', borderRadius: moderateScale(14), padding: moderateScale(16), alignItems: 'center', marginBottom: moderateScale(16), borderWidth: 1, borderColor: '#BFDBFE' },
  refLabel: { fontSize: moderateScale(12), color: colors.textSecondary, marginBottom: 6, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  refNumber: { fontSize: moderateScale(22), fontWeight: '900', color: colors.primary, letterSpacing: 1 },
  card: { backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), marginBottom: moderateScale(12), borderWidth: 1, borderColor: colors.border },
  cardTitle: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary, marginBottom: moderateScale(12) },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderColor: colors.border },
  summaryRowLast: { borderBottomWidth: 0 },
  summaryLabel: { fontSize: moderateScale(13), color: colors.textSecondary, width: moderateScale(60) },
  summaryValue: { flex: 1, fontSize: moderateScale(13), color: colors.textPrimary, fontWeight: '500', textAlign: 'right' },
  totalPaid: { fontWeight: '800', color: colors.primary, fontSize: moderateScale(15) },
  addressRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 10 },
  addressText: { flex: 1, fontSize: moderateScale(14), color: colors.textPrimary, fontWeight: '500' },
  instructionNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, backgroundColor: '#FEF9C3', borderRadius: 8, padding: 10, marginBottom: 12 },
  instructionText: { flex: 1, fontSize: moderateScale(12), color: colors.textSecondary },
  directionsBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderColor: colors.primary, borderRadius: 8, padding: 10, justifyContent: 'center' },
  directionsBtnText: { fontSize: moderateScale(14), color: colors.primary, fontWeight: '600' },
  ownerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: { width: moderateScale(42), height: moderateScale(42), borderRadius: moderateScale(21), backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontSize: moderateScale(17), fontWeight: '700' },
  ownerInfo: { flex: 1 },
  ownerName: { fontSize: moderateScale(14), fontWeight: '700', color: colors.textPrimary },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 2 },
  ownerRating: { fontSize: moderateScale(12), color: colors.textSecondary },
  msgBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.primary, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  msgBtnText: { color: '#fff', fontSize: moderateScale(12), fontWeight: '600' },
  primaryBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(14), marginBottom: moderateScale(10) },
  primaryBtnText: { color: '#fff', fontSize: moderateScale(15), fontWeight: '700' },
  outlineBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1.5, borderColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(13), marginBottom: moderateScale(16) },
  outlineBtnText: { color: colors.primary, fontSize: moderateScale(15), fontWeight: '600' },
  emailNote: { textAlign: 'center', fontSize: moderateScale(12), color: colors.textSecondary },
});