import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  content: {
    marginBottom: 20,
    paddingLeft: moderateScale(10),
    paddingRight: moderateScale(10),
  },
  trailerCard: {
    // alignItems: 'center',
    // gap: 12,
    // // backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    padding: moderateScale(12),
    marginBottom: moderateScale(20),
    borderWidth: 1,
    borderColor: colors.border,
  },
  InfoTrailor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  trailerThumb: {
    width: moderateScale(100),
    height: moderateScale(100),
    borderRadius: moderateScale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailerInfo: { flex: 1 },
  trailerTitle: {
    fontSize: moderateScale(15),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  trailerCategory: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  ownerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  ownerCapacityText: {
    fontSize: moderateScale(12),
    fontWeight: '400',
    color: colors.textSecondary,
  },
  ownerRatingText: {
    fontSize: moderateScale(13),
    color: '#F59E0B',
    fontWeight: '400',
  },
  pricePill: {
    backgroundColor: '#EFF6FF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  pricePillText: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.primary,
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(10),
    marginTop: moderateScale(4),
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  dateBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(10),
    padding: moderateScale(12),
    backgroundColor: colors.surface,
  },
  dateBtnLabel: { fontSize: moderateScale(11), color: colors.textSecondary },
  dateBtnValue: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: 2,
  },
  durationChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EFF6FF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  durationText: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '600',
  },
  fieldLabel: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 8,
    marginTop: 4,
  },
  timeOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: moderateScale(20),
  },
  timeChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  timeChipText: { fontSize: moderateScale(13), color: colors.textSecondary },
  timeChipTextActive: { color: '#fff', fontWeight: '600' },
  priceCard: {
    marginBottom: moderateScale(20),
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  priceLabel: { fontSize: moderateScale(14), color: colors.textSecondary },
  priceValue: {
    fontSize: moderateScale(14),
    color: colors.textPrimary,
    fontWeight: '600',
  },
  totalRow: { borderBottomWidth: 0, paddingTop: 12, marginTop: 4 },
  totalLabel: {
    fontSize: moderateScale(16),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  totalValue: {
    fontSize: moderateScale(18),
    fontWeight: '800',
    color: colors.primary,
  },
  depositNote: { paddingTop: moderateScale(20) },
  depositNoteText: {
    flex: 1,
    fontSize: moderateScale(12),
    lineHeight:10,
    color: colors.textSecondary,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: moderateScale(12),
    padding: moderateScale(14),
    marginBottom: 8,
    backgroundColor: '#EFF6FF',
  },
  paymentText: {
    flex: 1,
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  selectedDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  addCardBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: moderateScale(10),
    marginBottom: moderateScale(16),
  },
  addCardText: {
    fontSize: moderateScale(14),
    color: colors.primary,
    fontWeight: '500',
  },
  verificationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F0FDF4',
    borderRadius: moderateScale(12),
    padding: moderateScale(14),
    marginBottom: moderateScale(16),
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  verificationInfo: { flex: 1 },
  verificationTitle: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  verificationStatus: {
    fontSize: moderateScale(12),
    color: colors.success,
    marginTop: 2,
  },
  notesInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: moderateScale(10),
    padding: moderateScale(12),
    fontSize: moderateScale(14),
    color: colors.textPrimary,
    backgroundColor: colors.surface,
    minHeight: moderateScale(80),
    textAlignVertical: 'top',
  },
  footer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(16),
  },
  footerTotal: {
    fontSize: moderateScale(18),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  footerNote: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  confirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(0),
    paddingVertical: moderateScale(13),
  },
  confirmBtnDisabled: { opacity: 0.7 },
  confirmBtnText: {
    color: '#fff',
    fontSize: moderateScale(15),
    fontWeight: '700',
  },
  calendarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  calendarSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: moderateScale(16),
    paddingBottom: moderateScale(30),
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  calendarTitle: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  Rentercard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: moderateScale(4),

    marginBottom: moderateScale(0),
  },
  RentercardRow: { gap: moderateScale(12) },
  RentercardTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  RentercardSub: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: moderateScale(3),
  },
  locationCard: {},
  locationCardTitle: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  locationAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',

    gap: moderateScale(8),
  },
  locationAddress: {
    flex: 1,
    fontSize: moderateScale(12),
    color: colors.textSecondary,
  },
  CancellationPolicyLabel: {
    fontSize: moderateScale(14),
    color: colors.black,
    fontWeight: '600',
  },
  CancellationPolicyText: {
    fontSize: moderateScale(12),
    color: colors.textPrimary,
    fontWeight: '400',
   paddingTop:moderateScale(10)
  },
  terms: {
    fontSize: moderateScale(12),
    color: '#6B7280',
    lineHeight: moderateScale(18),
    marginTop: moderateScale(2),
    marginBottom: moderateScale(20),
  },

  termsBold: {
    fontWeight: '700',
    color: colors.primary,
  },
});
