import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';
export const styles =  StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(12), gap: 12, borderBottomWidth: 1, borderColor: colors.border },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: moderateScale(18), fontWeight: '700', color: colors.textPrimary },
  statusBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(10) },
  statusBannerText: { fontSize: moderateScale(14), fontWeight: '600' },
  stepRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(24), paddingVertical: moderateScale(16) },
  stepItem: { alignItems: 'center', gap: 4 },
  stepCircle: { width: moderateScale(30), height: moderateScale(30), borderRadius: moderateScale(15), borderWidth: 2, borderColor: '#D1D5DB', alignItems: 'center', justifyContent: 'center' },
  stepCircleActive: { borderColor: colors.primary },
  stepCircleDone: { backgroundColor: colors.success, borderColor: colors.success },
  stepNum: { fontSize: moderateScale(13), fontWeight: '700', color: '#9CA3AF' },
  stepNumActive: { color: colors.primary },
  stepLabel: { fontSize: moderateScale(10), color: '#9CA3AF', fontWeight: '500' },
  stepLabelActive: { color: colors.primary },
  stepLine: { flex: 1, height: 2, backgroundColor: '#D1D5DB', marginBottom: moderateScale(16) },
  stepLineDone: { backgroundColor: colors.success },
  content: { padding: moderateScale(16) },
  stepTitle: { fontSize: moderateScale(18), fontWeight: '800', color: colors.textPrimary, marginBottom: 4 },
  stepSubtitle: { fontSize: moderateScale(13), color: colors.textSecondary, marginBottom: moderateScale(20), lineHeight: 18 },
  fieldLabel: { fontSize: moderateScale(13), fontWeight: '600', color: colors.textPrimary, marginBottom: 8, marginTop: 4 },
  ownerTypeRow: { flexDirection: 'row', gap: 8, marginBottom: moderateScale(16) },
  typeChip: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.border },
  typeChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  typeChipText: { fontSize: moderateScale(12), color: colors.textSecondary },
  typeChipTextActive: { color: '#fff', fontWeight: '600' },
  uploadBox: { borderWidth: 2, borderColor: colors.border, borderStyle: 'dashed', borderRadius: moderateScale(12), padding: moderateScale(20), alignItems: 'center', gap: 8, marginBottom: moderateScale(14), backgroundColor: colors.surface },
  uploadBoxDone: { borderColor: colors.success, borderStyle: 'solid', backgroundColor: '#F0FDF4' },
  uploadText: { fontSize: moderateScale(14), color: colors.textSecondary, fontWeight: '500' },
  uploadSubtext: { fontSize: moderateScale(11), color: colors.textDisabled },
  requirementsList: { backgroundColor: colors.surface, borderRadius: moderateScale(10), padding: moderateScale(12), gap: 6, marginBottom: moderateScale(20) },
  requirementItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  requirementText: { fontSize: moderateScale(13), color: colors.textSecondary },
  nextBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(14) },
  nextBtnText: { color: '#fff', fontSize: moderateScale(15), fontWeight: '700' },
  declarationCard: { backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), borderWidth: 1, borderColor: colors.border, marginBottom: moderateScale(16) },
  declarationTitle: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary, marginBottom: 8 },
  declarationText: { fontSize: moderateScale(13), color: colors.textSecondary, lineHeight: 20, marginBottom: 14 },
  acceptRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, borderTopWidth: 1, borderColor: colors.border, paddingTop: 12 },
  checkbox: { width: 22, height: 22, borderRadius: 4, borderWidth: 2, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  acceptText: { flex: 1, fontSize: moderateScale(13), color: colors.textPrimary },
  navBtns: { flexDirection: 'row', gap: 10, marginTop: moderateScale(10) },
  prevBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1, borderColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(13) },
  prevBtnText: { color: colors.primary, fontSize: moderateScale(14), fontWeight: '600' },
  nextBtn2: { flex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: colors.primary, borderRadius: moderateScale(12), paddingVertical: moderateScale(13) },
  submitBtn: { flex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: colors.success, borderRadius: moderateScale(12), paddingVertical: moderateScale(13) },
  reviewCard: { backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), borderWidth: 1, borderColor: colors.border, marginBottom: moderateScale(14) },
  reviewRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderColor: colors.border },
  reviewLabel: { flex: 1, fontSize: moderateScale(13), color: colors.textSecondary },
  reviewValue: { fontSize: moderateScale(13), color: colors.textPrimary, fontWeight: '600' },
  reviewNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#EFF6FF', borderRadius: 10, padding: 12, marginBottom: moderateScale(16) },
  reviewNoteText: { flex: 1, fontSize: moderateScale(12), color: colors.textSecondary, lineHeight: 18 },
  pendingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: moderateScale(24) },
  pendingTitle: { fontSize: moderateScale(24), fontWeight: '800', color: colors.textPrimary, marginTop: 16, marginBottom: 8 },
  pendingSubtitle: { fontSize: moderateScale(14), color: colors.textSecondary, textAlign: 'center', lineHeight: 20, marginBottom: 24 },
  pendingCard: { width: '100%', backgroundColor: colors.surface, borderRadius: moderateScale(14), padding: moderateScale(16), borderWidth: 1, borderColor: colors.border, gap: 12, marginBottom: 24 },
  pendingRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  pendingItemText: { flex: 1, fontSize: moderateScale(14), color: colors.textPrimary },
  backBtn2: { backgroundColor: colors.primary, borderRadius: moderateScale(12), paddingHorizontal: moderateScale(24), paddingVertical: moderateScale(13) },
  backBtn2Text: { color: '#fff', fontSize: moderateScale(15), fontWeight: '700' },
});