import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from "../../Constants/Colors"
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(12), gap: 12, borderBottomWidth: 1, borderColor: colors.border },
  backBtn: { padding: 4 },
  headerTitle: { flex: 1, fontSize: moderateScale(18), fontWeight: '700', color: colors.textPrimary },
  badge: { backgroundColor: colors.error, borderRadius: 10, paddingHorizontal: 7, paddingVertical: 2 },
  badgeText: { color: '#fff', fontSize: moderateScale(11), fontWeight: '700' },
  tabBar: { flexDirection: 'row', borderBottomWidth: 1, borderColor: colors.border, paddingHorizontal: moderateScale(16) },
  tab: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: moderateScale(10), borderBottomWidth: 2, borderColor: 'transparent' },
  tabActive: { borderBottomColor: colors.primary },
  tabText: { fontSize: moderateScale(14), color: colors.textSecondary, fontWeight: '500' },
  tabTextActive: { color: colors.primary, fontWeight: '700' },
  tabBadge: { backgroundColor: colors.warning, borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  tabBadgeText: { color: '#fff', fontSize: moderateScale(10), fontWeight: '700' },
  list: { padding: moderateScale(16), gap: 12 },
  card: { backgroundColor: '#fff', borderRadius: moderateScale(14), borderWidth: 1, borderColor: colors.border, overflow: 'hidden' },
  cardTop: { padding: moderateScale(14), gap: 10 },
  renterRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatar: { width: moderateScale(40), height: moderateScale(40), borderRadius: moderateScale(20), backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontSize: moderateScale(16), fontWeight: '700' },
  renterInfo: { flex: 1 },
  renterNameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  renterName: { fontSize: moderateScale(14), fontWeight: '700', color: colors.textPrimary },
  renterMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  renterMetaText: { fontSize: moderateScale(12), color: colors.textSecondary },
  dot: { color: colors.textSecondary },
  statusBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4 },
  statusText: { fontSize: moderateScale(10), fontWeight: '700' },
  trailerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderRadius: moderateScale(8), padding: moderateScale(8) },
  trailerThumb: { width: moderateScale(36), height: moderateScale(36), borderRadius: moderateScale(8), alignItems: 'center', justifyContent: 'center' },
  trailerName: { fontSize: moderateScale(13), fontWeight: '600', color: colors.textPrimary },
  trailerType: { fontSize: moderateScale(11), color: colors.textSecondary },
  detailsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  detailItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailText: { fontSize: moderateScale(13), color: colors.textSecondary },
  totalPrice: { fontSize: moderateScale(16), fontWeight: '800', color: colors.primary },
  expiryBanner: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FEF9C3', borderRadius: 8, padding: 8 },
  expiryText: { flex: 1, fontSize: moderateScale(12), color: '#92400E' },
  rejectionNote: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FEE2E2', borderRadius: 8, padding: 8 },
  rejectionText: { flex: 1, fontSize: moderateScale(12), color: colors.error },
  cardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, padding: moderateScale(10), borderTopWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  viewDetail: { fontSize: moderateScale(13), color: colors.primary, fontWeight: '600' },
  emptyState: { alignItems: 'center', paddingTop: moderateScale(60), gap: 8 },
  emptyTitle: { fontSize: moderateScale(16), fontWeight: '600', color: colors.textSecondary },
});