import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from "../../../Constants/Colors"

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: moderateScale(16), paddingVertical: moderateScale(12), gap: 12, borderBottomWidth: 1, borderColor: colors.border },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: moderateScale(18), fontWeight: '700', color: colors.textPrimary },
  content: { padding: moderateScale(16) },
  welcomeCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#EFF6FF', borderRadius: moderateScale(14), padding: moderateScale(14), marginBottom: moderateScale(12), borderWidth: 1, borderColor: '#BFDBFE' },
  avatar: { width: moderateScale(46), height: moderateScale(46), borderRadius: moderateScale(23), backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontSize: moderateScale(18), fontWeight: '800' },
  welcomeInfo: { flex: 1 },
  welcomeName: { fontSize: moderateScale(15), fontWeight: '700', color: colors.textPrimary },
  memberSince: { fontSize: moderateScale(12), color: colors.textSecondary, marginTop: 2 },
  verifiedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#F0FDF4', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 5, borderWidth: 1, borderColor: '#BBF7D0' },
  verifiedText: { fontSize: moderateScale(12), color: colors.success, fontWeight: '600' },
  alertCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderRadius: moderateScale(10), padding: moderateScale(12), marginBottom: 8, borderLeftWidth: 4, borderWidth: 1, borderColor: colors.border },
  alertText: { flex: 1, fontSize: moderateScale(13), color: colors.textPrimary },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginVertical: moderateScale(16) },
  statCard: { width: '47%', backgroundColor: colors.surface, borderRadius: moderateScale(12), padding: moderateScale(14), borderWidth: 1, borderColor: colors.border },
  statIcon: { width: moderateScale(36), height: moderateScale(36), borderRadius: moderateScale(10), alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  statValue: { fontSize: moderateScale(20), fontWeight: '800', color: colors.textPrimary },
  statLabel: { fontSize: moderateScale(11), color: colors.textSecondary, marginTop: 2 },
  sectionTitle: { fontSize: moderateScale(16), fontWeight: '700', color: colors.textPrimary, marginBottom: moderateScale(10) },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: moderateScale(10) },
  seeAll: { fontSize: moderateScale(13), color: colors.primary, fontWeight: '500' },
  quickActions: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: moderateScale(20) },
  quickAction: { alignItems: 'center', gap: 6 },
  quickActionIcon: { width: moderateScale(52), height: moderateScale(52), borderRadius: moderateScale(14), alignItems: 'center', justifyContent: 'center' },
  quickActionLabel: { fontSize: moderateScale(11), color: colors.textSecondary, fontWeight: '500' },
  listingCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, borderRadius: moderateScale(12), padding: moderateScale(12), marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  listingThumb: { width: moderateScale(48), height: moderateScale(48), borderRadius: moderateScale(10), alignItems: 'center', justifyContent: 'center' },
  listingInfo: { flex: 1 },
  listingName: { fontSize: moderateScale(14), fontWeight: '700', color: colors.textPrimary },
  listingType: { fontSize: moderateScale(12), color: colors.textSecondary, marginTop: 2 },
  listingRight: { alignItems: 'flex-end', gap: 4 },
  statusBadge: { borderRadius: 4, paddingHorizontal: 6, paddingVertical: 3 },
  statusText: { fontSize: moderateScale(11), fontWeight: '600' },
  listingPrice: { fontSize: moderateScale(13), fontWeight: '700', color: colors.textPrimary },
  bookingCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, borderRadius: moderateScale(12), padding: moderateScale(12), marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  bookingThumb: { width: moderateScale(44), height: moderateScale(44), borderRadius: moderateScale(10), alignItems: 'center', justifyContent: 'center' },
  bookingInfo: { flex: 1 },
  bookingRenter: { fontSize: moderateScale(13), fontWeight: '700', color: colors.textPrimary },
  bookingTrailer: { fontSize: moderateScale(12), color: colors.textSecondary },
  bookingDates: { fontSize: moderateScale(11), color: colors.primary, marginTop: 2 },
  bookingPrice: { fontSize: moderateScale(15), fontWeight: '800', color: colors.primary },
});