import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import colors from '../../../Constants/Colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  content: { padding: moderateScale(16) },
  welcomeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EFF6FF',
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    marginBottom: moderateScale(16),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  avatar: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: moderateScale(24),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: moderateScale(20), fontWeight: '800' },
  welcomeInfo: { flex: 1 },
  welcomeName: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  memberSince: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F0FDF4',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  verifiedText: {
    fontSize: moderateScale(12),
    color: colors.success,
    fontWeight: '600',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: moderateScale(20),
  },
  statCard: {
    width: '47%',
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    padding: moderateScale(14),
    borderWidth: 1,
    borderColor: colors.border,
  },
  statIconWrap: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(10),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: moderateScale(22),
    fontWeight: '800',
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(10),
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: moderateScale(10),
  },
  seeAll: {
    fontSize: moderateScale(13),
    color: colors.primary,
    fontWeight: '500',
  },
  upcomingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    padding: moderateScale(12),
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  upcomingThumb: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  upcomingInfo: { flex: 1 },
  upcomingTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  upcomingDates: {
    fontSize: moderateScale(12),
    color: colors.textSecondary,
    marginTop: 2,
  },
  upcomingPrice: {
    fontSize: moderateScale(15),
    fontWeight: '800',
    color: colors.primary,
  },
  spendCard: {
    backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    marginBottom: moderateScale(20),
    borderWidth: 1,
    borderColor: colors.border,
  },
  spendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: moderateScale(16),
  },
  spendLabel: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    textAlign: 'center',
  },
  spendAmount: {
    fontSize: moderateScale(18),
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginTop: 2,
  },
  spendDivider: { width: 1, backgroundColor: colors.border },
  barChart: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: moderateScale(70),
  },
  barItem: { alignItems: 'center', gap: 4 },
  barWrapper: { height: moderateScale(60), justifyContent: 'flex-end' },
  bar: { width: moderateScale(28), borderRadius: 4 },
  barLabel: { fontSize: moderateScale(11), color: colors.textSecondary },
  savedList: { gap: 10, paddingBottom: 4, marginBottom: moderateScale(20) },
  savedCard: {
    width: moderateScale(110),
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  savedThumb: {
    height: moderateScale(70),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  heartIcon: { position: 'absolute', top: 6, right: 6 },
  savedTitle: {
    fontSize: moderateScale(12),
    fontWeight: '700',
    color: colors.textPrimary,
    padding: 8,
    paddingBottom: 2,
  },
  savedMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 8,
  },
  savedRating: { fontSize: moderateScale(12), color: colors.textSecondary },
  savedPrice: {
    fontSize: moderateScale(12),
    fontWeight: '700',
    color: colors.primary,
    padding: 8,
    paddingTop: 2,
  },
  activityCard: {
    backgroundColor: colors.surface,
    borderRadius: moderateScale(14),
    padding: moderateScale(16),
    borderWidth: 1,
    borderColor: colors.border,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingBottom: moderateScale(14),
    marginBottom: moderateScale(14),
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  activityItemLast: { paddingBottom: 0, marginBottom: 0, borderBottomWidth: 0 },
  activityIconWrap: {
    width: moderateScale(34),
    height: moderateScale(34),
    borderRadius: moderateScale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityInfo: { flex: 1 },
  activityText: {
    fontSize: moderateScale(13),
    color: colors.textPrimary,
    lineHeight: 18,
  },
  activityTime: {
    fontSize: moderateScale(11),
    color: colors.textSecondary,
    marginTop: 3,
  },
});
